version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: nextask_server
    ports:
      - "3000:3000"
    env_file:
      - server/.env

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: nextask_client
    ports:
      - "8080:80"
    env_file:
      - client/.env
    depends_on:
      - server
